# .github/workflows/deploy.yml
# Deploy an Angular SPA to GitHub Pages.
# This version prints the Angular project list, picks the correct app,
# forces a known output folder, and validates that index.html exists.

name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ "main" ]      # change if your default branch has a different name
  workflow_dispatch:          # allow manual runs

# -------------------------------------------------
# Permissions – needed for the deploy action to push
# -------------------------------------------------
permissions:
  contents: write   # allows creation/modification of gh‑pages
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      # -------------------------------------------------
      # 1️⃣ Checkout the repository
      # -------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------------------------------
      # 2️⃣ Set up Node.js (Angular CLI needs ≥ 20)
      # -------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"   # Angular CLI minimum version
          cache: "npm"

      # -------------------------------------------------
      # 3️⃣ Install npm dependencies (includes @angular/cli)
      # -------------------------------------------------
      - name: Install dependencies
        run: npm ci

      # -------------------------------------------------
      # 4️⃣ Show the angular.json file (debug)
      # -------------------------------------------------
      - name: Dump angular.json
        run: |
          echo "===== angular.json ====="
          cat angular.json
          echo "========================"

      # -------------------------------------------------
      # 5️⃣ Determine the **application** project name
      # -------------------------------------------------
      - name: Find Angular app project
        id: find-app
        run: |
          # List all keys under "projects"
          ALL=$(jq -r '.projects | keys[]' angular.json)
          echo "All projects found: $ALL"

          # Prefer the project that has a "build" architect entry and is NOT an e2e project
          APP=$(jq -r '
            .projects
            | to_entries
            | map(select(.value.architect?.build != null))
            | map(select(.key | test("e2e") | not))
            | .[0].key // empty
          ' angular.json)

          if [[ -z "$APP" ]]; then
            echo "⚠️ Could not auto‑detect an app project. Falling back to first project."
            APP=$(echo "$ALL" | head -n1)
          fi

          echo "Selected Angular app project: $APP"
          echo "project=$APP" >> $GITHUB_OUTPUT

      # -------------------------------------------------
      # 6️⃣ Build Angular – force a known output folder
      # -------------------------------------------------
      - name: Build Angular app
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          PROJECT: ${{ steps.find-app.outputs.project }}
        run: |
          echo "🔧 Building project '$PROJECT' for repo: $REPO_NAME"
          # Force the output folder to ./dist/out so we always know where it lands
          npx ng build "$PROJECT" \
            --configuration production \
            --output-path=dist/out \
            --base-href="/${REPO_NAME}/"

      # -------------------------------------------------
      # 7️⃣ List what the build produced (debug)
      # -------------------------------------------------
      - name: List build output
        run: |
          echo "=== CONTENTS OF ./dist/out ==="
          ls -R ./dist/out || echo "❌ ./dist/out does not exist"
          echo "=== END OF LIST ==="

      # -------------------------------------------------
      # 8️⃣ Verify index.html exists, add SPA fallback & .nojekyll
      # -------------------------------------------------
      - name: Add SPA fallback & .nojekyll
        run: |
          BUILD_DIR=./dist/out
          if [[ ! -f "${BUILD_DIR}/index.html" ]]; then
            echo "❌ index.html not found in ${BUILD_DIR}. Build likely failed or wrong project."
            exit 1
          fi
          cp "${BUILD_DIR}/index.html" "${BUILD_DIR}/404.html"
          touch "${BUILD_DIR}/.nojekyll"
          echo "✅ Created 404.html and .nojekyll in ${BUILD_DIR}"

      # -------------------------------------------------
      # 9️⃣ Deploy to GitHub Pages (creates/updates gh‑pages)
      # -------------------------------------------------
      - name: Deploy to GitHub Pages
        id: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages                # target branch
          folder: ./dist/out               # the folder we just prepared
          clean: true                     # wipe old files before copy
          token: ${{ secrets.GITHUB_TOKEN }}
